var words = [
{text: 'North', size: 238},
{text: 'West', size: 218},
{text: 'South', size: 183},
{text: 'East', size: 163},
{text: 'NW', size: 102},
{text: 'Phoenix', size: 101},
{text: 'NE', size: 96},
{text: 'California', size: 86},
{text: 'SW', size: 85},
{text: 'US', size: 83},
{text: 'Seattle', size: 74},
{text: 'CA', size: 72},
{text: 'NUFORC', size: 71},
{text: 'Arizona', size: 67},
{text: 'Texas', size: 64},
{text: 'Florida', size: 53},
{text: 'WA', size: 52},
{text: 'Venus', size: 51},
{text: 'AZ', size: 47},
{text: 'Las Vegas', size: 47},
{text: 'UFOs', size: 46},
{text: 'Washington', size: 43},
{text: 'Ohio', size: 43},
{text: 'Jupiter', size: 42},
{text: 'Lake', size: 41},
{text: 'Colorado', size: 40},
{text: 'Los Angeles', size: 40},
{text: 'NY', size: 38},
{text: 'Missouri', size: 36},
{text: 'Michigan', size: 35},
{text: 'San Diego', size: 34},
{text: 'Earth', size: 34},
{text: 'New York', size: 32},
{text: 'Illinois', size: 32},
{text: 'Oregon', size: 31},
{text: 'SE', size: 31},
{text: 'Portland', size: 30},
{text: 'TX', size: 29},
{text: 'U.S.', size: 29},
{text: 'moon', size: 28},
{text: 'Canada', size: 27},
{text: 'Southwest', size: 27},
{text: 'New Mexico', size: 27},
{text: 'Houston', size: 27},
{text: 'Atlanta', size: 27},
{text: 'Pacific', size: 26},
{text: 'Nevada', size: 26},
{text: 'MO', size: 26},
{text: 'Interstate', size: 26},
{text: 'NJ', size: 25},
{text: 'PA', size: 25},
{text: 'Austin', size: 25},
{text: 'Chicago', size: 24},
{text: 'Dallas', size: 24},
{text: 'Albuquerque', size: 24},
{text: 'Pennsylvania', size: 24},
{text: 'Las', size: 23},
{text: 'Northwest', size: 23},
{text: 'Triangular', size: 23},
{text: 'Telephoned Report', size: 22},
{text: 'Columbus', size: 21},
{text: 'New', size: 21},
{text: 'San Antonio', size: 21},
{text: 'Ontario', size: 20},
{text: 'Indiana', size: 20},
{text: 'Northeast', size: 20},
{text: 'Denver', size: 19},
{text: 'MUFON', size: 19},
{text: 'Tucson', size: 19},
{text: 'IL', size: 19},
{text: 'NC', size: 19},
{text: 'VA', size: 19},
{text: 'Mars', size: 19},
{text: 'Wisconsin', size: 18},
{text: 'Spokane', size: 18},
{text: 'USA', size: 18},
{text: 'MI', size: 18},
{text: 'OH', size: 18},
{text: 'OR', size: 18},
{text: 'New Jersey', size: 18},
{text: 'North West', size: 18},
{text: 'San Francisco', size: 18},
{text: 'Mexico', size: 18},
{text: 'Orange', size: 18},
{text: 'San Jose', size: 17},
{text: 'N', size: 17},
{text: 'Utah', size: 17},
{text: 'FL', size: 17},
{text: 'North East', size: 17},
{text: 'Triangle', size: 17},
{text: 'dusk', size: 17},
{text: 'Kansas City', size: 16},
{text: 'Lake Michigan', size: 16},
{text: 'Alabama', size: 16},
{text: 'Virginia', size: 16},
{text: 'Lake Erie', size: 16},
{text: 'Iowa', size: 16},
{text: 'Maine', size: 15},
{text: 'CO', size: 15},
{text: 'Toronto', size: 15},
{text: 'Gulf', size: 15},
{text: 'South East', size: 15},
{text: 'United States', size: 15},
{text: 'Vancouver', size: 15},
{text: 'Kansas', size: 15},
{text: 'Black Triangle', size: 14},
{text: 'LA', size: 14},
{text: 'Springfield', size: 14},
{text: 'W', size: 13},
{text: 'Montana', size: 13},
{text: 'Kentucky', size: 13},
{text: 'San', size: 13},
{text: 'Idaho', size: 13},
{text: 'Route', size: 13},
{text: 'TN', size: 13},
{text: 'Tx', size: 13},
{text: 'S.E.', size: 13},
{text: 'Coast', size: 13},
{text: 'Pacific Ocean', size: 13},
{text: 'Detroit', size: 13},
{text: 'St. Louis', size: 13},
{text: 'Miami', size: 12},
{text: 'Colorado Springs', size: 12},
{text: 'Cleveland', size: 12},
{text: 'our Center', size: 12},
{text: 'Hope', size: 12},
{text: 'St Louis', size: 12},
{text: 'South West', size: 12},
{text: 'Philadelphia', size: 12},
{text: 'Scottsdale', size: 12},
{text: 'Manhattan', size: 12},
{text: 'Tacoma', size: 12},
{text: 'Maryland', size: 11},
{text: 'Georgia', size: 11},
{text: 'NV', size: 11},
{text: 'PD', size: 11},
{text: 'N.E.', size: 11},
{text: 'Dayton', size: 11},
{text: 'south east', size: 11},
{text: 'Salt Lake City', size: 11},
{text: 'Orlando', size: 11},
{text: 'Tampa', size: 11},
{text: 'Sedona', size: 11},
{text: 'Hollywood', size: 11},
{text: 'Pittsburgh', size: 11},
{text: 'Nashville', size: 10},
{text: 'Milwaukee', size: 10},
{text: 'NUFORC NOTE', size: 10},
{text: 'Columbia', size: 10},
{text: 'Minneapolis', size: 10},
{text: 'Santa', size: 10},
{text: 'Boston', size: 10},
{text: 'ohio', size: 10},
{text: 'North Carolina', size: 10},
{text: 'It', size: 10},
{text: 'MA', size: 10},
{text: 'Pa', size: 10},
{text: 'Sacramento', size: 10},
{text: 'Long Island', size: 10},
{text: 'Tennessee', size: 10},
{text: 'Oval', size: 10},
{text: 'Memphis', size: 10},
{text: 'Hudson River', size: 10},
{text: 'Mississippi', size: 10},
{text: 'Wyoming', size: 10},
{text: 'Gulf of Mexico', size: 10},
{text: 'Northern', size: 10},
{text: 'Sky Harbor', size: 10},
{text: 'Spring', size: 10},
{text: 'Arkansas', size: 10},
{text: 'Salt Lake', size: 10},
{text: 'Cape Canaveral', size: 10},
{text: 'U. S.', size: 10},
{text: 'S', size: 9},
{text: 'Light', size: 9},
{text: 'Calif', size: 9},
{text: 'Albany', size: 9},
{text: 'california', size: 9},
{text: 'Staten Island', size: 9},
{text: 'Ca', size: 9},
{text: 'NH', size: 9},
{text: 'Mesa', size: 9},
{text: 'Southeast', size: 9},
{text: 'Wa', size: 9},
{text: 'Laughlin', size: 9},
{text: 'north west', size: 9},
{text: 'Moon', size: 9},
{text: 'Large', size: 9},
{text: 'Reno', size: 9},
{text: 'NYC', size: 9},
{text: 'Newark', size: 9},
{text: 'COLOR', size: 9},
{text: 'Pine', size: 9},
{text: 'Puget Sound', size: 9},
{text: 'Bellevue', size: 9},
{text: 'Wallops Island', size: 9},
{text: 'Hwy', size: 9},
{text: 'New York City', size: 9},
{text: 'Ill', size: 9},
{text: 'Brooklyn', size: 8},
{text: 'L.A.', size: 8},
{text: 'Minnesota', size: 8},
{text: 'Island', size: 8},
{text: 'Hawaii', size: 8},
{text: 'South Carolina', size: 8},
{text: 'KY', size: 8},
{text: 'MN', size: 8},
{text: 'NM', size: 8},
{text: 'Canton', size: 8},
{text: 'Fort Worth', size: 8},
{text: 'S.W.', size: 8},
{text: 'Palm Springs', size: 8},
{text: 'Burbank', size: 8},
{text: 'Olympic Mountains', size: 8},
{text: 'Baltimore', size: 8},
{text: 'Flagstaff', size: 8},
{text: 'Renton', size: 8},
{text: 'Atlantic', size: 8},
{text: 'Jacksonville', size: 8},
{text: 'Gulf Breeze', size: 8},
{text: 'Richmond', size: 8},
{text: 'Massachusetts', size: 8},
{text: 'San Fernando Valley', size: 7},
{text: 'Roswell', size: 7},
{text: 'Vandenburg', size: 7},
{text: 'USAF', size: 7},
{text: 'Casa Grande', size: 7},
{text: 'Bay', size: 7},
{text: 'Sun', size: 7},
{text: 'Belgium', size: 7},
{text: 'Rhode Island', size: 7},
{text: 'Az', size: 7},
{text: 'Sea-Tac', size: 7},
{text: 'GA', size: 7},
{text: 'Fl', size: 7},
{text: 'Ga', size: 7},
{text: 'Hamilton', size: 7},
{text: 'Lake Ontario', size: 7},
{text: 'Washington State', size: 7},
{text: 'Santa Monica', size: 7},
{text: 'south west', size: 7},
{text: 'Aberdeen', size: 7},
{text: 'Redding', size: 7},
{text: 'Atlantic Ocean', size: 7},
{text: 'Indianapolis', size: 7},
{text: 'Oklahoma', size: 7},
{text: 'Lancaster', size: 7},
{text: 'Southern', size: 7},
{text: 'Yuma', size: 7},
{text: 'Santa Clara', size: 7},
{text: 'Salem', size: 7},
{text: 'Delaware', size: 7},
{text: 'Monterey', size: 7},
{text: 'Las Cruces', size: 7},
{text: 'Calif.', size: 7},
{text: 'El Paso', size: 7},
{text: 'Bakersfield', size: 6},
{text: 'Fort', size: 6},
{text: 'Kent', size: 6},
{text: 'Arlington', size: 6},
{text: 'Everett', size: 6},
{text: 'Fresno', size: 6},
{text: 'LAX', size: 6},
{text: 'Santa Ana', size: 6},
{text: 'China', size: 6},
{text: 'Edwards', size: 6},
{text: 'DFW', size: 6},
{text: 'O&apos;Hare', size: 6},
{text: 'AL', size: 6},
{text: 'Santa Fe', size: 6},
{text: 'canada', size: 6},
{text: 'north east', size: 6},
{text: 'S.', size: 6},
{text: 'South Dakota', size: 6},
{text: 'Anchorage', size: 6},
{text: 'Los', size: 6},
{text: '3am', size: 6},
{text: 'Lake Washington', size: 6},
{text: 'N.W.', size: 6},
{text: 'Ft Lauderdale', size: 6},
{text: 'seattle', size: 6},
{text: 'Louisville', size: 6},
{text: 'Rochester', size: 6},
{text: 'Mississippi River', size: 6},
{text: 'Mexico City', size: 6},
{text: 'colorado', size: 6},
{text: 'Saginaw', size: 6},
{text: 'Lexington', size: 6},
{text: 'Fort Collins', size: 6},
{text: 'Southern California', size: 6},
{text: 'Vandenberg AFB', size: 6},
{text: 'Columbia River', size: 6},
{text: 'Vietnam', size: 6},
{text: 'Pensacola', size: 6},
{text: 'Erie', size: 6},
{text: 'Cheyenne', size: 6},
{text: 'washington', size: 6},
{text: 'Whidbey Island', size: 6},
{text: 'Vegas', size: 6},
{text: '000', size: 6}
];